= ミニブログアプリ開発カリキュラム
:toc: left

== びっくりブログについて
=== 標準機能
==== User機能
* ログイン
* ログアウト
* サインイン

==== ブログ機能
* ブログ投稿機能
* ブログ編集機能
* ブログ削除機能
* 未ログイン状態で全ブログを閲覧可能

=== 追加機能
* Facebookログイン機能
* 投稿/編集/削除後のリダイレクト機能
** 3秒後、ルートにリダイレクト 

=== 苦労した点
==== リダイレクトするJQueryの読み込みで思わぬトラブル
フロントエンドの開発が苦手なため、まだ得意なJQueryやバックエンドなどの拡張開発などで変化を出したかった +
UXを考えてクリックなどの動作を少なくすることを目指し追加機能として画面のリダイレクトを選定

リダイレクトの処理を適応する画面が +

* create
* update
* delete

上記の3つのみのため従来のapplication.html.erbのヘッダ部に記載する方式では +
application.js内の `//= require_tree .` が `assets/javascript` 配下のファイルを読み込んでしまうため +
全てのページで3秒毎にルートにリダイレクトしてしまうのでjsの読み込みの段階から修正が必要


全体の読み込みを削除 +
.assets/javascript/application.js
```js
//= require_tree .  =>削除
```

個別にコンパイルを行うように定義 +
.config/initializers/assets.rb
[source,ruby]
----
Rails.application.config.assets.precompile += %w( redirect.js ) 
----


これで各ページの先頭でjsファイルを読み込むようにすればリダイレクトされるようになる

=== やり残したこと
* twitter/googleログインにも対応できるようにしたかった
* twitterに投稿できる機能をつけたかった
* ブログ投稿時にctrl(or command)+enterで投稿できるようにしたかった


=== 進歩
==== 機能追加でなかなかない経験ができた
oauth2の実装のためにdeviseで生成されるファイルの編集、設定ファイルの編集など +
基盤をいじったことで調査方法や前後の変化を見ることができたのが有益だった +
サーバサイドエンジニアとして転職したいと考えているため、今回に止まらず積極的にいろいろな機能を試していきたい

== このドキュメントについて 
本ドキュメントはAsciidocで記述しgithubのgithub pagesの機能を用いて公開している +
今後、チーム開発を行ううえでのナレッジ管理のためにこのようなドキュメントを用いた情報共有を行っていきたいと考えている
